### ISSUE TITLE
Had to remove chianti.ioneq file

### ISSUE THREAD

**Issue by sahiggin** [chianti-atomic/ChiantiPy#141] opened 2017-07-05 21:09 UTC
I just installed ChiantiPy by cloning from this repo and running python setup.py install. Operating system is Windows 10 running Anaconda Python 2.7.12. 

I set the environment variables and got ChiantiPy.core to import, but got all sorts of attribute errors when running the test lines. Finally realized that I was getting a warning on import, "found more than one ioneq file." When I removed the chianti.ioneq file inside ioneq/, it broke ChiantiPy. I went into ioneq/PaxHeader.23462 and removed that chianti.ioneq file, and now everything works fine. 

So, it works. But strange...

**Comment by wtbarnes** [comment] 2017-07-06 11:09
Would you mind including the exact lines that you ran to get this error so that we could try to reproduce it? Additionally, what Python distribution are you using (e.g. Anaconda, Enthought, etc.,)?

Currently we are not testing on Windows so if it is an OS specific problem, I'm not surprised we haven't come across it.

**Comment by sahiggin** [comment] 2017-07-06 15:23
Python distribution is Anaconda Python 2.7.12. 

```
import os
os.environ["XUVTOP"]="C:\\Users\\shiggins\\Documents\\CHIANTI"
os.environ["HOME"]="C:\\Users\\shiggins\\Documents\\CHIANTI"
import ChiantiPy.core as ch
import numpy as np
t = 10.**(5.8 + 0.05*np.arange(21.))
fe14 = ch.ion('fe_14', temperature=t, eDensity=1.e+9, em=1.e+27)
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\shiggins\AppData\Local\Continuum\Anaconda2\lib\site-packages\chiantipy-0.7.dev506-py2.7.egg\ChiantiPy\core\Ion.py", line 114, in __init__
    self.Defaults = chdata.Defaults
AttributeError: 'module' object has no attribute 'Defaults'
```
This error occurs with chianti.ioneq present in PaxHeaders.23462 folder. If I remove the file (I just threw it on the Desktop), no errors - all works fine.

**Comment by kdere** [comment] 2017-07-06 16:26
try:
`import ChiantiPy.tools.data as chdata`
`for akey in chdata.Defaults.keys():  print(akey)`

this should give a list of things like:
abundfile
wavelength
flux
ioneqfile
gui
let us know what happens

**Comment by sahiggin** [comment] 2017-07-06 16:34
Import succeeds, command returns:
ioneqfile
wavelength
gui
abundfile
flux

That's all, though.

**Comment by kdere** [comment] 2017-07-06 17:42
It looks like you are able to import the attribute that has the names of various default values
for example
chdata.Defaults['ioneqfile'] should give the the name 'chianti' and this corresponds to the ioneq file chianti.ioneq
you are using ChiantiPy version 0.7.0... which should be OK.
I also do not understand 

> PaxHeader.23462

has

 that got something to do with the Anaconda package?
I am at a bit of a  loss here

**Comment by sahiggin** [comment] 2017-07-06 17:47
No, it's part of the gzipped Chianti database that you have to download prior to installing ChiantiPy. 

From the instructions at http://chiantipy.sourceforge.net/installing.html:

> The gzipped data tar ball can be downloaded from the CHIANTI website
> - put the file in a convenient directory, cd to the directory and untar the file
> - ChiantiPy uses the environment variable XUVTOP to find the database. Set XUVTOP to the name of the directory where the CHIANTI data tarball was placed. 

So when you unzip those files, you get a series of folders - mostly element names, and then some metadata. There is a folder ioneq, which contains a file chianti.ioneq. There is also a folder ioneq/PaxHeaders.23462, which also contains a file chianti.ioneq. If I don't remove the second copy, ChiantiPy complains about it on import of ChiantiPy.core ("found more than one ioneq file.") I then get the errors that I reported. If I remove the file from that folder, everything behaves fine. I just wanted to let you know about that.

**Comment by wtbarnes** [comment] 2017-07-06 18:15
Hmm ok so this seems to be an issue with the version of the database you have rather than the code itself. I do not think this has anything to do with the specific distribution. Like Ken, I have no idea what the "PaxHeader" files are all about. Maybe there are problems with the zipped database currently on the CHIANTI website? 

Just as a side note, the SourceForge docs that you referenced are out of date and need to be deprecated. Please refer to the (hopefully) up-to-date documentation at http://chiantipy.readthedocs.io/en/latest/

Sorry for the inconvenience and thanks for reporting this issue. I'm away from my office at the moment but will try to figure out what the issue is with these duplicate ioneq files. We'll keep the issue open until we've found a more definite answer.

**Comment by sahiggin** [comment] 2017-07-06 18:57
No problem, thanks for the response. Good to know about the SourceForge docs.

**Comment by kdere** [comment] 2017-07-06 20:04
I just downloaded the database from chiantidatabase.org and it did not have the "PaxHeader" things in it.  You might want to do a clean install it your have more problems like that.

**Comment by wtbarnes** [comment] 2017-07-08 19:14
@sahiggin what utility are you using to extract/unzip the CHIANTI tarball?

**Comment by wtbarnes** [comment] 2017-07-18 16:04
I've downloaded the latest tarball from [the CHIANTI webpage](http://www.chiantidatabase.org/) and using the command,

```shell
$ tar xvzf /path/to/tarball.gz
```

on Mac OS X v10.11.6 (El Capitan) I do not get any of these PaxHeader files. A bit of googling seems to suggest this is an OS or zip-tool dependent issue:

* [PaxHeader folder in prebuilt packages](https://groups.drupal.org/node/315878)
* [#1413 tar file contents reported incorrectly (extra PaxHeaders.### folders)](https://sourceforge.net/p/sevenzip/bugs/1413/)
* [includes ././@PaxHeader which confuses older tar versions](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=230872)

I would try a few different zip tools, perhaps playing around with the different command-line options each offers. As you say, one option is obviously just to remove these files manually.

Either way, this seems to not be related to the ChiantiPy code itself so I'm going to go ahead and close this issue. Feel free to continue this thread if you're still having issues with these files and we can try to figure it out.

**Closed as completed by wtbarnes** 2017-07-18 16:04 UTC
